class_name ManualClues
extends RefCounted

const CLUES: Dictionary = {
	"bàn trang điểm": "Đồ nội thất có gương và ngăn kéo, dùng khi chải tóc hoặc chuẩn bị trước khi ra ngoài.",
	"bao gối": "Lớp vải bọc bên ngoài ruột gối để giữ sạch và tạo cảm giác êm khi nằm.",
	"chăn": "Tấm vải dày dùng để đắp khi ngủ hoặc khi trời lạnh.",
	"công tắc điện": "Bộ phận dùng để bật hoặc tắt nguồn điện cho đèn và thiết bị.",
	"cửa sổ": "Khoảng mở trên tường giúp phòng có ánh sáng và không khí.",
	"đèn bàn": "Đèn nhỏ đặt trên bàn, thường dùng để đọc sách hoặc làm việc.",
	"đèn ngủ": "Đèn ánh sáng dịu để trong phòng khi nghỉ ngơi ban đêm.",
	"đệm": "Tấm lót êm đặt trên giường để nằm thoải mái hơn.",
	"đồng hồ báo thức": "Thiết bị đặt giờ kêu để nhắc người dùng thức dậy.",
	"giường": "Đồ nội thất chính trong phòng ngủ, dùng để nằm nghỉ.",
	"giường hai tầng": "Loại giường có hai chỗ nằm xếp chồng lên nhau để tiết kiệm diện tích.",
	"gối": "Vật mềm kê đầu khi ngủ.",
	"gối ôm": "Gối dài dùng để ôm hoặc kê người khi nằm.",
	"gương": "Bề mặt phản chiếu hình ảnh, thường dùng để soi.",
	"màn cửa": "Tấm vải che cửa sổ để chắn sáng hoặc tạo riêng tư.",
	"móc treo quần áo": "Vật dùng để treo áo quần cho gọn và ít nhăn.",
	"ngăn kéo": "Hộc trượt ra vào trong tủ hoặc bàn để cất đồ nhỏ.",
	"ra trải giường": "Tấm vải phủ lên đệm để giữ sạch chỗ nằm.",
	"rương": "Hòm lớn có nắp, dùng để cất giữ đồ đạc.",
	"tiếng ngáy": "Âm thanh phát ra khi một người thở lúc ngủ.",
	"tủ quần áo": "Tủ lớn dùng để treo và cất quần áo.",
	"ngáp": "Phản xạ há miệng hít sâu khi buồn ngủ hoặc mệt.",
	"ngáy": "Thở phát ra âm thanh trong lúc ngủ.",
	"ngủ": "Trạng thái nghỉ ngơi tự nhiên của cơ thể.",
	"nằm mơ": "Trải nghiệm hình ảnh hoặc câu chuyện xuất hiện trong khi ngủ.",

	"giây": "Đơn vị thời gian rất ngắn, bằng một phần sáu mươi của phút.",
	"phút": "Đơn vị thời gian gồm sáu mươi giây.",
	"giờ": "Đơn vị thời gian gồm sáu mươi phút.",
	"thứ": "Tên gọi vị trí của ngày trong một tuần.",
	"tuần": "Khoảng thời gian gồm bảy ngày liên tiếp.",
	"tháng": "Đơn vị lịch dài khoảng ba mươi ngày.",
	"quý": "Khoảng thời gian gồm ba tháng trong một năm.",
	"năm": "Khoảng thời gian Trái Đất đi hết một vòng quanh Mặt Trời.",
	"thập kỷ": "Khoảng thời gian gồm mười năm.",
	"thế kỷ": "Khoảng thời gian gồm một trăm năm.",
	"thiên niên kỷ": "Khoảng thời gian gồm một nghìn năm.",
	"mùa": "Giai đoạn trong năm có kiểu thời tiết và sinh hoạt đặc trưng.",
	"buổi sáng": "Khoảng thời gian đầu ngày sau khi trời sáng.",
	"buổi trưa": "Khoảng thời gian giữa ngày, quanh lúc mặt trời lên cao.",
	"buổi chiều": "Khoảng thời gian sau trưa và trước tối.",
	"buổi tối": "Khoảng thời gian sau hoàng hôn, thường dành cho nghỉ ngơi.",
	"nửa đêm": "Thời điểm giữa đêm, thường tính vào lúc mười hai giờ đêm.",
	"hoàng hôn": "Khoảnh khắc mặt trời lặn, bầu trời chuyển màu cuối ngày.",
	"bình minh": "Khoảnh khắc trời sáng lên khi mặt trời sắp mọc.",
	"ngày mai": "Ngày liền sau ngày hiện tại.",
	"ngày nghỉ": "Ngày không phải làm việc hoặc học tập theo lịch thường lệ.",
	"ngày lễ": "Ngày có ý nghĩa kỷ niệm, tín ngưỡng hoặc văn hóa đặc biệt.",

	"bàn chải": "Dụng cụ có lông nhỏ dùng để chà sạch răng, tóc hoặc bề mặt.",
	"bọt xà phòng": "Lớp bong bóng nổi lên khi xà phòng hòa với nước và được chà xát.",
	"bồn cầu": "Thiết bị vệ sinh dùng để đi vệ sinh và xả nước làm sạch.",
	"bồn rửa tay": "Chậu cố định có vòi nước dùng để rửa tay hoặc rửa mặt.",
	"bồn tắm": "Bồn lớn chứa nước để ngâm người khi tắm.",
	"cống thoát nước": "Đường dẫn đưa nước bẩn ra khỏi sàn hoặc bồn rửa.",
	"dao cạo râu": "Dụng cụ có lưỡi sắc dùng để làm sạch râu sát da.",
	"dầu gội đầu": "Dung dịch dùng để làm sạch tóc và da đầu.",
	"dầu xả": "Sản phẩm dùng sau khi gội để tóc mềm và dễ chải hơn.",
	"giấy vệ sinh": "Loại giấy mềm dùng để lau chùi khi đi vệ sinh.",
	"kem cạo râu": "Bọt hoặc kem bôi lên da để cạo râu dễ hơn.",
	"kem đánh răng": "Chất dạng kem dùng với bàn chải để làm sạch răng.",
	"keo xịt tóc": "Sản phẩm xịt giúp giữ nếp tóc sau khi tạo kiểu.",
	"khăn": "Tấm vải thấm nước dùng để lau người, tay hoặc mặt.",
	"lược": "Dụng cụ có răng nhỏ dùng để chải và gỡ tóc.",
	"máy sấy tóc": "Thiết bị thổi hơi nóng hoặc gió để làm khô tóc.",
	"móc treo": "Vật dùng để treo khăn, quần áo hoặc đồ dùng nhỏ.",
	"nhíp": "Dụng cụ nhỏ có hai đầu kẹp dùng để nhổ hoặc gắp vật rất nhỏ.",
	"nước súc miệng": "Dung dịch dùng để làm sạch khoang miệng và giảm mùi hơi thở.",
	"sữa rửa mặt": "Sản phẩm làm sạch da mặt khỏi bụi, dầu và chất bẩn.",
	"sữa tắm": "Dung dịch dùng để làm sạch cơ thể khi tắm.",
	"vòi nước": "Thiết bị điều khiển dòng nước chảy ra.",
	"vòi sen": "Đầu phun nước thành tia nhỏ dùng khi tắm.",
	"xà bông": "Chất tẩy rửa dạng bánh hoặc dung dịch dùng để làm sạch.",

	"cạo trọc": "Kiểu tóc được cắt sát hoặc cạo gần hết tóc trên đầu.",
	"đầu đinh": "Kiểu tóc rất ngắn, tóc dựng đều như đầu đinh.",
	"hói đầu": "Tình trạng tóc rụng nhiều làm lộ da đầu.",
	"mái ngố": "Kiểu tóc mái cắt ngang trán, tạo vẻ trẻ hoặc ngây ngô.",
	"bím": "Tóc được tết thành dải bằng cách đan nhiều lọn lại với nhau.",
	"búi": "Tóc được gom và cuộn thành khối ở sau hoặc trên đầu.",
	"buộc hai bên": "Kiểu tóc chia đôi rồi buộc thành hai phần ở hai phía đầu.",
	"cá đối": "Kiểu tóc ngắn phía trước và hai bên, dài hơn ở phía sau.",
	"chẻ ngôi giữa": "Kiểu tóc rẽ đường ngôi ở giữa đầu.",
	"dài": "Trạng thái tóc có độ dài vượt xuống vai hoặc hơn.",
	"đuôi ngựa": "Kiểu tóc gom lại và buộc phía sau, rủ xuống như đuôi ngựa.",
	"gợn sóng": "Tóc có nếp uốn nhẹ thành những đường lượn mềm.",
	"hai mái": "Kiểu tóc có hai phần tóc mái rẽ sang hai bên.",
	"húi cua": "Kiểu tóc cắt rất ngắn và đều quanh đầu.",
	"ngang vai": "Độ dài tóc chạm hoặc gần chạm vai.",
	"ngắn": "Trạng thái tóc có độ dài ít, không phủ xa khỏi đầu.",
	"nhuộm": "Việc đổi màu tóc bằng thuốc tạo màu.",
	"thẳng": "Tóc không xoăn hoặc uốn, sợi tóc rủ theo đường tương đối thẳng.",
	"uốn lọn": "Kiểu tóc được tạo thành các lọn cong rõ.",
	"xoăn": "Tóc có nhiều vòng cong hoặc nếp cuộn tự nhiên hay tạo kiểu.",

	"bắn bi": "Trò chơi dùng viên bi nhỏ, người chơi bắn để chạm mục tiêu.",
	"bầu cua tôm cá": "Trò chơi gieo xúc xắc có hình các con vật để đặt cược vui.",
	"bịt mắt bắt dê": "Trò chơi một người bị che mắt tìm bắt những người còn lại.",
	"chọi gà": "Trò chơi hoặc cuộc thi cho hai con gà đấu với nhau.",
	"chơi chuyền": "Trò chơi tung bắt que hoặc vật nhỏ theo nhịp tay.",
	"cờ caro": "Trò chơi đánh dấu ô trên bàn lưới để tạo hàng liên tiếp.",
	"cờ cá ngựa": "Trò chơi bàn cờ đưa quân hình ngựa về đích theo xúc xắc.",
	"cờ người": "Trò chơi cờ dùng người thật đóng vai các quân cờ.",
	"cờ tướng": "Trò chơi chiến thuật trên bàn cờ với quân tướng, xe, pháo, mã.",
	"cờ vây": "Trò chơi đặt quân đen trắng để chiếm đất trên bàn kẻ ô.",
	"cướp cờ": "Trò chơi vận động hai đội chạy giành vật làm cờ ở giữa sân.",
	"đá cầu": "Trò chơi dùng chân đá quả cầu qua lại, không để rơi xuống đất.",
	"đánh quay": "Trò chơi làm con quay xoay bằng dây hoặc lực đánh.",
	"đấu vật": "Hoạt động thi sức dùng tay và thân để vật đối thủ xuống.",
	"đếm sao": "Trò chơi trẻ em gắn với việc nhìn trời và đếm các ngôi sao.",
	"đi cà kheo": "Trò chơi hoặc biểu diễn đi trên hai cây chống cao.",
	"kéo co": "Trò chơi hai đội kéo hai đầu dây để phân thắng thua.",
	"kéo cưa lừa xẻ": "Trò chơi trẻ em vừa hát vừa kéo tay qua lại theo nhịp.",
	"oẳn tù tì": "Trò chơi ra dấu tay kéo, búa, bao để phân thắng thua.",
	"ô ăn quan": "Trò chơi dân gian dùng bàn ô và sỏi để tính nước đi.",
	"mèo đuổi chuột": "Trò chơi vòng tròn trong đó một người đuổi bắt người khác.",
	"nhảy bao bố": "Trò chơi chui chân vào bao rồi nhảy về đích.",
	"nhảy dây": "Hoạt động nhảy qua sợi dây quay theo nhịp.",
	"nhảy lò cò": "Trò chơi nhảy bằng một chân qua các ô hoặc vạch.",
	"nhảy sạp": "Điệu chơi hoặc múa bước qua các thanh tre gõ nhịp.",
	"rồng rắn lên mây": "Trò chơi nối hàng dài, vừa hát vừa tránh người bắt.",
	"thả diều": "Hoạt động cho diều bay lên nhờ gió và dây điều khiển.",
	"trốn tìm": "Trò chơi một người đi tìm những người đang ẩn nấp.",

	"bình xịt hơi cay": "Dụng cụ phun chất cay gây khó chịu ở mắt và mũi để tự vệ.",
	"bom": "Vũ khí chứa chất nổ, phát nổ để gây sức phá hoại lớn.",
	"bồ cào": "Dụng cụ có răng dài, trong ngữ cảnh vũ khí có thể dùng để cào hoặc chống trả.",
	"chùy": "Vũ khí cầm tay có đầu nặng, dùng để đánh bằng lực mạnh.",
	"côn nhị khúc": "Vũ khí gồm hai đoạn côn nối bằng dây hoặc xích ngắn.",
	"cung tên": "Vũ khí bắn mũi tên nhờ lực căng của dây cung.",
	"dao": "Dụng cụ có lưỡi sắc, có thể dùng để cắt hoặc làm vũ khí gần.",
	"đại bác": "Pháo lớn bắn đạn nặng đi xa bằng sức nổ.",
	"đạn": "Vật được bắn ra từ súng hoặc pháo.",
	"đao": "Vũ khí có lưỡi dài và cong, dùng để chém.",
	"đinh ba": "Vũ khí hoặc dụng cụ có ba mũi nhọn ở đầu cán.",
	"giáo": "Vũ khí cán dài có mũi nhọn để đâm.",
	"khiên": "Vật che chắn cầm tay dùng để phòng thủ trước đòn tấn công.",
	"kích": "Vũ khí cán dài có lưỡi nhọn hoặc lưỡi cong ở đầu.",
	"kiếm": "Vũ khí lưỡi dài, thường dùng để chém hoặc đâm.",
	"lao": "Vũ khí dạng giáo nhẹ, có thể phóng đi.",
	"lưỡi lê": "Lưỡi dao gắn ở đầu súng để đánh gần.",
	"lựu đạn": "Vũ khí nổ nhỏ, thường được ném bằng tay.",
	"mã tấu": "Dao lớn lưỡi dài, thường dùng để chặt hoặc làm vũ khí.",
	"máy bắn đá": "Cỗ máy cổ dùng lực bật để phóng đá hoặc vật nặng.",
	"mìn": "Vũ khí nổ được đặt sẵn, kích hoạt khi có tác động.",
	"ná": "Dụng cụ bắn vật nhỏ bằng dây cao su căng.",
	"ngư lôi": "Vũ khí tự hành dưới nước dùng để tấn công tàu.",
	"nỏ": "Vũ khí bắn tên bằng cơ cấu cung gắn trên thân cứng.",
	"phi tiêu": "Vật nhọn nhỏ được phóng hoặc ném vào mục tiêu.",
	"rìu": "Dụng cụ có lưỡi nặng, có thể dùng để chặt hoặc chiến đấu.",
	"roi da": "Dải da dài dùng để quất.",
	"súng cối": "Loại pháo bắn đạn theo đường vòng cung từ nòng ngắn.",
	"súng ngắn": "Súng cầm một tay, kích thước nhỏ.",
	"súng trường": "Súng dài tì vai, thường dùng để bắn xa hơn súng ngắn.",
	"tên lửa": "Vũ khí bay nhờ động cơ phản lực hoặc nhiên liệu đẩy.",
	"thuốc độc": "Chất gây hại hoặc gây chết khi vào cơ thể.",
	"thuốc nổ": "Chất hóa học phát nổ khi được kích hoạt.",
	"thủy lôi": "Mìn đặt dưới nước để phá hủy tàu thuyền.",

	"chị hằng": "Nhân vật truyền thuyết gắn với cung trăng trong đêm rằm tháng tám.",
	"chú cuội": "Nhân vật dân gian được kể là ngồi dưới gốc cây trên mặt trăng.",
	"thỏ ngọc": "Hình tượng con thỏ sống trên cung trăng trong truyền thuyết Á Đông.",
	"ông địa": "Nhân vật đeo mặt nạ vui nhộn thường xuất hiện trong múa lân.",
	"cây đa": "Loài cây gắn với chuyện Chú Cuội và hình ảnh mặt trăng.",
	"cung trăng": "Không gian tưởng tượng trên mặt trăng nơi các nhân vật truyền thuyết sinh sống.",
	"trăng tròn": "Mặt trăng hiện đầy đặn, sáng rõ vào đêm rằm.",
	"bánh trung thu": "Bánh truyền thống dùng trong dịp rằm tháng tám.",
	"mặt nạ": "Đồ che mặt dùng để hóa trang khi vui chơi lễ hội.",
	"đèn lồng": "Đèn trang trí có khung và vỏ màu, thường cầm đi rước.",
	"đèn ông sao": "Đèn Trung thu hình ngôi sao năm cánh.",
	"đèn cá chép": "Đèn lồng tạo hình cá chép, thường dành cho trẻ em.",
	"đèn kéo quân": "Đèn lồng có hình quay bên trong nhờ hơi nóng.",
	"tò he": "Đồ chơi dân gian nặn từ bột màu.",
	"lễ rước đèn": "Hoạt động đi thành đoàn cầm đèn trong đêm Trung thu.",
	"rước đèn": "Việc cầm đèn lồng đi chơi hoặc diễu hành trong lễ hội.",
	"múa lân": "Màn múa dùng đầu lân và trống để tạo không khí lễ hội.",
	"múa rồng": "Màn biểu diễn nhiều người điều khiển thân rồng dài.",
	"ngắm trăng": "Hoạt động nhìn và thưởng thức vẻ đẹp của trăng đêm rằm.",
	"phá cỗ": "Hoạt động cùng ăn mâm bánh trái sau phần vui chơi Trung thu.",

	"âm ly": "Thiết bị khuếch đại âm thanh trước khi phát ra loa.",
	"bàn sofa": "Bàn thấp đặt gần ghế sô pha trong phòng khách.",
	"bình hoa": "Vật chứa hoa để trang trí không gian.",
	"bức ảnh": "Hình được chụp hoặc in lại để lưu giữ khoảnh khắc.",
	"cây cảnh": "Cây trồng trong chậu để trang trí nhà cửa.",
	"đèn chùm": "Đèn trang trí treo trên trần, thường có nhiều nhánh sáng.",
	"điều hòa": "Thiết bị làm mát hoặc điều chỉnh nhiệt độ không khí.",
	"điều khiển tivi": "Thiết bị cầm tay dùng để đổi kênh và chỉnh tivi từ xa.",
	"đồng hồ treo tường": "Đồng hồ gắn trên tường để xem giờ.",
	"gạt tàn thuốc": "Vật đựng tàn và mẩu thuốc lá.",
	"ghế bành": "Ghế có tay vịn và lưng tựa, thường ngồi thư giãn.",
	"ghế đẩu": "Ghế nhỏ, thường không có lưng tựa.",
	"ghế sô pha": "Ghế dài có đệm mềm, dùng để ngồi tiếp khách hoặc nghỉ ngơi.",
	"kệ": "Đồ có nhiều tầng ngang để đặt sách, đồ trang trí hoặc vật dụng.",
	"lịch": "Bảng hoặc sổ ghi ngày tháng để theo dõi thời gian.",
	"loa": "Thiết bị phát âm thanh ra ngoài.",
	"nệm lót ghế": "Tấm đệm đặt trên ghế để ngồi êm hơn.",
	"quạt điện": "Thiết bị dùng điện để tạo luồng gió làm mát.",
	"quạt trần": "Quạt gắn trên trần nhà để làm mát không gian rộng.",
	"thảm": "Tấm trải trên sàn để trang trí, giữ ấm hoặc chống trơn.",
	"thùng rác": "Vật chứa rác thải trong nhà.",
	"tivi": "Thiết bị hiển thị hình ảnh và âm thanh để xem chương trình.",
	"tranh": "Tác phẩm hình ảnh dùng để trang trí hoặc thưởng thức.",
	"tủ sách": "Tủ hoặc kệ dùng để cất và trưng bày sách.",

	"bít tất": "Đồ mang ở chân để giữ ấm hoặc đi cùng giày.",
	"cây tầm gửi": "Loài cây trang trí gắn với phong tục hôn dưới cành trong Giáng sinh.",
	"cây thông": "Loài cây lá kim thường được trang trí trong mùa lễ cuối năm.",
	"cây thông noel": "Cây thông được trang trí đèn, quả châu và ngôi sao dịp Giáng sinh.",
	"chuông": "Vật phát âm thanh ngân vang, thường dùng làm biểu tượng lễ hội.",
	"dây đèn": "Chuỗi bóng đèn nhỏ dùng để trang trí.",
	"lò sưởi": "Nơi tạo hơi ấm trong nhà, gắn với hình ảnh mùa đông.",
	"nến": "Vật bằng sáp có tim cháy tạo ánh sáng.",
	"ngôi sao": "Hình trang trí năm cánh, thường đặt trên đỉnh cây thông.",
	"người tuyết": "Hình người nặn từ tuyết, biểu tượng mùa đông.",
	"ông già noel": "Nhân vật mặc đồ đỏ, được kể là mang quà cho trẻ em.",
	"ống khói": "Đường dẫn khói từ lò sưởi ra ngoài mái nhà.",
	"quà giáng sinh": "Món quà trao tặng trong dịp Giáng sinh.",
	"quả châu": "Quả trang trí tròn treo trên cây thông Noel.",
	"ruy băng": "Dải vải mảnh dùng để buộc nơ hoặc trang trí quà.",
	"thiệp giáng sinh": "Tấm thiệp gửi lời chúc trong mùa Giáng sinh.",
	"tuần lộc": "Loài hươu phương Bắc, gắn với xe kéo của Ông già Noel.",
	"vòng nguyệt quế giáng sinh": "Vòng lá trang trí treo cửa trong mùa Giáng sinh.",
	"xe trượt tuyết": "Phương tiện trượt trên tuyết, thường gắn với tuần lộc trong truyện lễ hội.",

	"bão": "Hiện tượng thời tiết có gió mạnh và mưa lớn trên diện rộng.",
	"bão cát": "Hiện tượng gió mạnh cuốn cát bụi dày đặc trong vùng khô hạn.",
	"bão tuyết": "Trận bão kèm tuyết rơi dày và gió lạnh mạnh.",
	"cháy rừng": "Đám cháy lan rộng trong khu vực rừng.",
	"dịch bệnh": "Bệnh lây lan nhanh trong cộng đồng hoặc trên diện rộng.",
	"động đất": "Sự rung chuyển của mặt đất do dịch chuyển trong lòng Trái Đất.",
	"hạn hán": "Tình trạng thiếu nước kéo dài do ít mưa.",
	"hố sụt": "Hố xuất hiện khi mặt đất bị sập xuống đột ngột.",
	"lốc xoáy": "Cột gió xoay mạnh có thể cuốn phá vật trên đường đi.",
	"lở đất": "Hiện tượng đất đá trượt xuống sườn dốc.",
	"lũ lụt": "Tình trạng nước dâng cao và tràn ngập vùng đất.",
	"mưa đá": "Mưa có hạt băng rơi xuống từ mây dông.",
	"nạn đói": "Tình trạng thiếu lương thực nghiêm trọng trên diện rộng.",
	"phun trào núi lửa": "Hiện tượng dung nham, tro và khí nóng thoát ra từ núi lửa.",
	"sa mạc hóa": "Quá trình đất màu mỡ trở nên khô cằn như sa mạc.",
	"sóng thần": "Sóng biển cực lớn thường do động đất dưới đáy biển gây ra.",
	"tuyết lở": "Khối tuyết lớn trượt nhanh xuống sườn núi.",

	"hôn lễ": "Nghi lễ chính thức đánh dấu việc kết hôn.",
	"chú rể": "Người nam kết hôn trong đám cưới.",
	"cô dâu": "Người nữ kết hôn trong đám cưới.",
	"nhà trai": "Gia đình hoặc họ hàng phía chú rể.",
	"nhà gái": "Gia đình hoặc họ hàng phía cô dâu.",
	"phù dâu": "Người hỗ trợ cô dâu trong lễ cưới.",
	"phù rể": "Người hỗ trợ chú rể trong lễ cưới.",
	"chủ hôn": "Người đại diện điều hành hoặc chứng kiến nghi thức cưới.",
	"giấy đăng ký kết hôn": "Văn bản pháp lý xác nhận quan hệ vợ chồng.",
	"đám hỏi": "Nghi lễ trước đám cưới để hai gia đình chính thức hứa gả.",
	"hủy hôn": "Việc chấm dứt kế hoạch kết hôn trước khi cưới.",
	"rước dâu": "Nghi thức đưa cô dâu về nhà chú rể.",
	"trao nhẫn": "Nghi thức hai người đeo nhẫn cho nhau trong lễ cưới.",
	"xe hoa": "Xe được trang trí để chở cô dâu chú rể.",
	"thiệp mời": "Tấm thiệp gửi khách để mời dự sự kiện.",
	"tiệc cưới": "Bữa tiệc mừng sau hoặc trong ngày cưới.",
	"của hồi môn": "Tài sản gia đình trao cho cô dâu khi về nhà chồng.",
	"nhẫn cưới": "Vòng đeo tay tượng trưng cho hôn nhân.",
	"váy cưới": "Trang phục cô dâu mặc trong lễ cưới.",
	"bó hoa cưới": "Bó hoa cô dâu cầm trong lễ cưới.",
	"bánh cưới": "Bánh dùng trong tiệc cưới, thường được trang trí nhiều tầng.",
	"trầu cau": "Lễ vật truyền thống tượng trưng cho hôn nhân.",
	"rượu sâm banh": "Loại rượu vang sủi bọt dùng để chúc mừng.",
	"quà cưới": "Món quà tặng cho đôi vợ chồng mới cưới.",
	"tiền mừng cưới": "Khoản tiền khách gửi để chúc mừng đám cưới.",
	"tuần trăng mật": "Kỳ nghỉ của đôi mới cưới sau lễ cưới.",

	"biển": "Vùng nước mặn rộng lớn nhưng nhỏ hơn đại dương.",
	"bãi biển": "Dải đất cát hoặc sỏi nằm sát mép biển.",
	"bờ biển": "Ranh giới nơi đất liền tiếp giáp với biển.",
	"vịnh": "Phần biển ăn sâu vào đất liền, thường được che chắn một phần.",
	"eo biển": "Dải nước hẹp nối hai vùng biển lớn.",
	"đảo": "Vùng đất được nước bao quanh ở mọi phía.",
	"mũi đất": "Phần đất nhô ra biển hoặc hồ.",
	"rạn san hô": "Cấu trúc dưới biển do san hô tạo thành, là nơi nhiều sinh vật sống.",
	"sóng": "Dao động nhấp nhô trên mặt nước do gió hoặc chuyển động gây ra.",
	"cát": "Hạt khoáng nhỏ thường phủ trên bãi biển.",
	"thủy triều": "Hiện tượng nước biển dâng lên và rút xuống theo chu kỳ.",
	"cảng biển": "Khu vực tàu thuyền neo đậu, bốc dỡ hàng hóa hoặc đón khách.",
	"hải đăng": "Tháp phát sáng giúp tàu thuyền định hướng ban đêm.",
	"khu nghỉ dưỡng": "Nơi lưu trú và thư giãn dành cho khách du lịch.",
	"tàu ngầm": "Phương tiện có thể di chuyển dưới mặt nước.",
	"du thuyền": "Tàu dùng cho du lịch, nghỉ dưỡng hoặc giải trí trên nước.",
	"thuyền buồm": "Thuyền di chuyển nhờ sức gió tác động lên buồm.",
	"ca nô": "Thuyền máy nhỏ chạy nhanh trên mặt nước.",
	"thợ lặn": "Người xuống dưới nước để làm việc, khám phá hoặc cứu hộ.",
	"người cứu hộ ở biển": "Người giám sát bãi biển và hỗ trợ khi có nguy hiểm dưới nước.",
	"phao cứu hộ": "Vật nổi dùng để giúp người dưới nước bám vào.",
	"thuyền cứu hộ": "Thuyền dùng để tiếp cận và cứu người gặp nạn trên nước.",
	"áo phao": "Áo nổi giúp người mặc không bị chìm dưới nước.",
	"chân vịt": "Dụng cụ đeo ở chân giúp bơi hoặc lặn nhanh hơn.",
	"kem chống nắng": "Sản phẩm bôi da để giảm tác hại của ánh nắng.",
	"đồ bơi": "Trang phục mặc khi bơi hoặc đi biển.",
	"cá voi": "Động vật biển có vú rất lớn, thở bằng phổi.",
	"cá mập": "Loài cá săn mồi lớn, có nhiều răng sắc.",
	"cá heo": "Động vật biển có vú thông minh, thường bơi theo đàn.",
	"cá ngựa": "Sinh vật biển nhỏ có đầu giống ngựa và thân cong.",
	"hải cẩu": "Động vật biển có vú, thân thon và chân biến thành vây.",
	"sứa": "Sinh vật biển thân mềm trong suốt, có tua có thể gây ngứa.",
	"mực": "Động vật biển thân mềm có tua và khả năng phun mực.",
	"bạch tuộc": "Động vật biển có tám tay tua và trí nhớ tốt.",
	"con trai": "Động vật thân mềm hai mảnh vỏ sống dưới nước.",
	"sao biển": "Sinh vật biển có thân hình giống ngôi sao.",
	"cua": "Động vật giáp xác có càng và mai cứng.",
	"ốc": "Động vật thân mềm thường có vỏ xoắn bảo vệ.",
	"sò": "Động vật thân mềm có hai mảnh vỏ, thường sống ở cát hoặc bùn biển.",
	"rùa": "Động vật có mai cứng, một số loài sống ở biển.",
	"rong biển": "Thực vật hoặc tảo sống trong nước biển.",
	"san hô": "Sinh vật biển nhỏ tạo thành quần thể cứng dưới nước.",
	"vỏ sò": "Lớp vỏ cứng bảo vệ cơ thể của sò.",
	"mòng biển": "Loài chim sống gần biển, thường bay tìm cá và thức ăn.",
	"chim hải âu": "Loài chim biển có cánh dài, bay tốt trên đại dương.",
	"chim yến": "Loài chim nhỏ, có tổ được dùng làm thực phẩm quý.",
	"thái bình dương": "Đại dương lớn nhất Trái Đất.",
	"đại tây dương": "Đại dương nằm giữa châu Mỹ, châu Âu và châu Phi.",
	"ấn độ dương": "Đại dương nằm phía nam châu Á và phía đông châu Phi.",
	"bắc băng dương": "Đại dương lạnh quanh vùng cực Bắc.",

	"bảng kiểm tra thị lực": "Bảng có chữ hoặc ký hiệu nhiều kích cỡ để đo khả năng nhìn.",
	"băng keo cá nhân": "Miếng dán nhỏ dùng để che và bảo vệ vết thương nhẹ.",
	"bông gòn": "Vật liệu mềm, thấm hút, thường dùng để lau hoặc sát khuẩn.",
	"cái cáng": "Dụng cụ dùng để khiêng người bị thương hoặc bệnh nhân.",
	"cái cân": "Dụng cụ đo khối lượng cơ thể hoặc đồ vật.",
	"cái nạng": "Dụng cụ chống đỡ giúp người bị đau chân di chuyển.",
	"cồn": "Dung dịch thường dùng để sát khuẩn.",
	"dao mổ": "Dụng cụ sắc dùng trong phẫu thuật.",
	"hộp cứu thương": "Hộp đựng vật dụng sơ cứu như băng, gạc và thuốc sát trùng.",
	"kéo y tế": "Kéo dùng trong chăm sóc y tế, thường để cắt băng gạc.",
	"khẩu trang y tế": "Vật che mũi miệng giúp hạn chế giọt bắn và bụi bẩn.",
	"ống nghe": "Dụng cụ bác sĩ dùng để nghe tim, phổi hoặc âm thanh trong cơ thể.",
	"ống tiêm": "Dụng cụ có kim dùng để tiêm thuốc hoặc lấy mẫu dịch.",
	"máy đo huyết áp": "Thiết bị dùng để kiểm tra áp lực máu trong động mạch.",
	"máy sốc điện": "Thiết bị cấp xung điện để hỗ trợ tim trong tình huống khẩn cấp.",
	"mặt nạ ôxi": "Mặt nạ giúp đưa khí ôxi đến người cần hỗ trợ hô hấp.",
	"nhiệt kế": "Dụng cụ đo nhiệt độ cơ thể.",
	"que đè lưỡi": "Que dẹt dùng để giữ lưỡi khi khám họng.",
	"que thử thai": "Dụng cụ kiểm tra dấu hiệu mang thai qua mẫu nước tiểu.",
	"xe lăn": "Ghế có bánh xe giúp người khó đi lại di chuyển.",

	"chũm chọe": "Nhạc cụ gõ gồm hai đĩa kim loại va vào nhau tạo tiếng vang.",
	"cồng chiêng": "Nhạc cụ gõ bằng đồng, âm vang, phổ biến trong văn hóa Tây Nguyên.",
	"đại phong cầm": "Nhạc cụ phím lớn tạo âm bằng luồng hơi qua ống.",
	"đàn bầu": "Nhạc cụ một dây của Việt Nam, tạo âm bằng cần rung và bầu cộng hưởng.",
	"đàn cello": "Nhạc cụ dây lớn, chơi bằng vĩ khi đặt giữa hai chân.",
	"đàn đá": "Nhạc cụ gõ cổ làm từ các thanh đá phát âm vang.",
	"đàn ghi ta": "Nhạc cụ dây có thùng cộng hưởng, thường gảy bằng tay hoặc phím.",
	"đàn hạc": "Nhạc cụ dây có khung lớn, dây căng thẳng đứng.",
	"đàn luýt": "Nhạc cụ dây cổ có thân tròn và cần đàn ngắn.",
	"đàn nhị": "Nhạc cụ hai dây của Việt Nam, chơi bằng vĩ.",
	"đàn organ": "Nhạc cụ phím điện tử mô phỏng nhiều âm sắc.",
	"đàn phong cầm": "Nhạc cụ kéo đẩy hộp hơi, bấm phím để phát âm.",
	"đàn piano": "Nhạc cụ phím dùng búa gõ vào dây để tạo âm.",
	"đàn tam thập lục": "Nhạc cụ dây Việt Nam có nhiều dây, gõ bằng que nhỏ.",
	"đàn tranh": "Nhạc cụ dây dài của Việt Nam, gảy bằng móng hoặc tay.",
	"đàn tỳ bà": "Nhạc cụ dây thân quả lê, gảy bằng tay.",
	"đàn ukulele": "Nhạc cụ dây nhỏ giống ghi ta, âm sáng và vui.",
	"đàn vi ô lông": "Nhạc cụ dây nhỏ chơi bằng vĩ, còn gọi là vĩ cầm.",
	"kèn harmonica": "Nhạc cụ thổi nhỏ, tạo âm khi luồng hơi đi qua lưỡi gà.",
	"kèn saxophone": "Nhạc cụ hơi kim loại có âm ấm, thường dùng trong jazz.",
	"kèn trumpet": "Nhạc cụ hơi kim loại có âm sáng và vang.",
	"kèn túi": "Nhạc cụ hơi có túi chứa khí và các ống phát âm.",
	"kẻng tam giác": "Nhạc cụ gõ bằng thanh kim loại uốn thành hình tam giác.",
	"mõ": "Nhạc cụ gõ bằng gỗ, tạo tiếng cộc đều.",
	"mộc cầm": "Nhạc cụ gõ gồm các thanh gỗ xếp theo cao độ.",
	"phách": "Nhạc cụ gõ nhỏ dùng để giữ nhịp.",
	"sáo": "Nhạc cụ thổi dạng ống có lỗ bấm.",
	"sênh tiền": "Nhạc cụ gõ dân gian có thanh gỗ và đồng xu tạo tiếng leng keng.",
	"trống": "Nhạc cụ gõ có mặt da căng trên thân rỗng.",
	"trống lắc tay": "Trống nhỏ có hạt hoặc dây gõ, phát âm khi lắc.",
	"tù và": "Nhạc cụ thổi làm từ sừng hoặc vỏ lớn, âm vang xa.",

	"não": "Cơ quan điều khiển hoạt động thần kinh, suy nghĩ và cảm giác.",
	"tuyến giáp": "Tuyến nội tiết ở cổ, tiết hormone điều hòa chuyển hóa.",
	"khí quản": "Ống dẫn không khí từ họng xuống phổi.",
	"thực quản": "Ống dẫn thức ăn từ miệng xuống dạ dày.",
	"mạch máu": "Đường ống trong cơ thể vận chuyển máu.",
	"phổi": "Cơ quan hô hấp giúp trao đổi ôxi và khí carbonic.",
	"tim": "Cơ quan bơm máu đi khắp cơ thể.",
	"gan": "Cơ quan lớn giúp chuyển hóa chất, lọc độc và tạo mật.",
	"dạ dày": "Cơ quan chứa và tiêu hóa thức ăn sau khi nuốt.",
	"lá lách": "Cơ quan liên quan đến máu và hệ miễn dịch.",
	"thận": "Cơ quan lọc máu và tạo nước tiểu.",
	"bàng quang": "Túi chứa nước tiểu trước khi thải ra ngoài.",
	"túi mật": "Túi nhỏ chứa mật do gan tạo ra.",
	"tụy": "Cơ quan tiết men tiêu hóa và hormone điều hòa đường huyết.",
	"tá tràng": "Đoạn đầu của ruột non ngay sau dạ dày.",
	"trực tràng": "Đoạn cuối của ruột già trước hậu môn.",
	"ruột non": "Đoạn ruột dài hấp thu phần lớn chất dinh dưỡng.",
	"ruột già": "Đoạn ruột hấp thu nước và tạo phân.",
	"ruột thừa": "Mẩu ruột nhỏ nối với ruột già, có thể bị viêm.",
	"hậu môn": "Lỗ cuối của ống tiêu hóa để thải phân.",

	"tết dương lịch": "Ngày đầu tiên của năm theo lịch dương.",
	"tết nguyên đán": "Dịp năm mới truyền thống theo âm lịch của người Việt.",
	"tất niên": "Bữa hoặc buổi sum họp cuối năm để khép lại năm cũ.",
	"giao thừa": "Thời khắc chuyển từ năm cũ sang năm mới.",
	"chợ hoa": "Nơi bán hoa và cây cảnh trước dịp Tết.",
	"hoa đào": "Loài hoa màu hồng đặc trưng ngày Tết ở miền Bắc.",
	"hoa mai": "Loài hoa vàng đặc trưng ngày Tết ở miền Nam.",
	"cây nêu": "Cây tre dựng ngày Tết theo phong tục truyền thống.",
	"cây quất": "Cây cảnh có quả vàng cam, tượng trưng cho sung túc ngày Tết.",
	"bánh chưng": "Bánh vuông làm từ gạo nếp, đậu xanh và thịt, gói lá dong.",
	"củ kiệu": "Món củ ngâm chua thường ăn kèm trong ngày Tết.",
	"hạt dưa": "Hạt rang màu đỏ hoặc nâu dùng để đãi khách ngày Tết.",
	"hạt hướng dương": "Hạt rang dùng làm món nhâm nhi khi trò chuyện.",
	"mứt": "Món ngọt làm từ trái cây hoặc củ quả rim đường.",
	"dưa hấu": "Quả lớn ruột đỏ, thường bày hoặc ăn trong dịp Tết.",
	"mâm ngũ quả": "Mâm bày năm loại quả tượng trưng cho ước vọng tốt lành.",
	"tiền lì xì": "Tiền mừng tuổi đặt trong phong bao đỏ.",
	"bao lì xì": "Phong bao nhỏ màu đỏ dùng để đựng tiền mừng tuổi.",
	"câu đối": "Cặp câu chữ treo ngày Tết để chúc điều tốt đẹp.",
	"pháo hoa": "Màn ánh sáng nổ trên trời trong dịp chào mừng.",
	"điều cấm kỵ": "Việc được tránh làm vì tin là không may trong dịp đầu năm.",
	"dọn dẹp nhà cửa": "Việc làm sạch và sắp xếp nhà trước năm mới.",
	"lau dọn bàn thờ": "Việc làm sạch nơi thờ cúng trước dịp lễ Tết.",
	"phóng sinh": "Việc thả sinh vật về tự nhiên như một hành động tạo phúc.",
	"xông đất": "Người đầu tiên đến nhà sau giao thừa theo phong tục Tết.",
	"xuất hành đầu năm": "Việc ra khỏi nhà lần đầu trong năm mới theo hướng hoặc giờ tốt.",
	"hái lộc": "Việc lấy nhành cây hoặc lộc tượng trưng cho may mắn đầu năm.",
	"chúc tết": "Việc gửi lời chúc tốt đẹp trong năm mới.",
	"tảo mộ": "Việc thăm và chăm sóc mộ phần tổ tiên.",
	"ông công": "Vị thần coi sóc đất đai, nhà cửa trong tín ngưỡng dân gian.",
	"ông táo": "Vị thần bếp được tiễn về trời vào cuối năm âm lịch.",

	"nông dân": "Người làm nghề trồng trọt hoặc chăn nuôi.",
	"gia súc": "Nhóm vật nuôi lớn như trâu, bò, lợn, dê, cừu.",
	"gia cầm": "Nhóm vật nuôi có lông vũ như gà, vịt, ngỗng.",
	"thủy sản": "Nguồn lợi hoặc sản phẩm từ sinh vật sống dưới nước.",
	"nông sản": "Sản phẩm thu được từ trồng trọt hoặc chăn nuôi.",
	"nhà kho": "Công trình dùng để cất giữ nông cụ, lương thực hoặc hàng hóa.",
	"nhà kính": "Nhà trồng cây có mái và vách trong suốt để kiểm soát môi trường.",
	"cánh đồng": "Khu đất rộng dùng để trồng lúa hoặc cây hoa màu.",
	"đồng cỏ": "Khu đất phủ cỏ, thường dùng cho vật nuôi ăn.",
	"cỏ khô": "Cỏ đã phơi khô để làm thức ăn cho gia súc.",
	"cỏ dại": "Cây mọc tự nhiên không được trồng, thường cạnh tranh với cây trồng.",
	"máy cắt cỏ": "Máy dùng để cắt ngắn cỏ.",
	"máy gặt đập liên hợp": "Máy thu hoạch lúa vừa gặt vừa tách hạt.",
	"máy kéo": "Xe máy công suất lớn dùng để kéo nông cụ trên đồng.",
	"cái cào": "Dụng cụ có răng dùng để gom cỏ, lá hoặc làm tơi đất.",
	"cần câu": "Dụng cụ gồm cần dài và dây để bắt cá.",
	"cuốc đất": "Dụng cụ dùng để xới hoặc bổ đất.",
	"cuốc chim": "Dụng cụ có đầu nhọn dùng để phá đất cứng hoặc đá.",
	"liềm": "Dụng cụ lưỡi cong dùng để cắt lúa, cỏ hoặc cây.",
	"xẻng": "Dụng cụ có bản rộng dùng để xúc đất, cát hoặc vật liệu.",
	"bình tưới nước": "Bình có vòi dùng để tưới cây.",
	"hạt giống": "Hạt được gieo để mọc thành cây mới.",
	"cái thang": "Dụng cụ có bậc dùng để leo lên cao.",
	"bù nhìn": "Hình nộm đặt trên ruộng để xua chim phá hoại.",
	"hàng rào": "Vật chắn bao quanh khu đất hoặc chuồng trại.",
	"xe cút kít": "Xe đẩy một bánh dùng để chở đất, phân hoặc nông sản.",
	"giếng": "Hố đào sâu lấy nước ngầm.",
	"cối xay gió": "Công trình dùng sức gió để xay hoặc bơm nước.",
	"máng ăn": "Vật dài đựng thức ăn cho vật nuôi.",
	"thức ăn cho gia súc": "Thức ăn chuẩn bị cho các vật nuôi lớn.",
	"chuồng bò": "Nơi nuôi nhốt hoặc che mưa nắng cho bò.",
	"chuồng gà": "Nơi nuôi nhốt hoặc cho gà nghỉ ban đêm.",
	"chuồng lợn": "Nơi nuôi nhốt lợn.",
	"chuồng ngựa": "Nơi nuôi và chăm sóc ngựa.",
	"trâu": "Vật nuôi lớn thường dùng kéo cày ở nông thôn.",
	"bò": "Vật nuôi lớn cho thịt, sữa hoặc sức kéo.",
	"lợn": "Vật nuôi thân tròn, thường được nuôi lấy thịt.",
	"dê": "Vật nuôi có sừng, ăn cỏ và leo trèo giỏi.",
	"cừu": "Vật nuôi có lông dày, cho len và thịt.",
	"ngựa": "Vật nuôi chạy nhanh, từng dùng để cưỡi và kéo xe.",
	"gà": "Gia cầm phổ biến, cho trứng và thịt.",
	"vịt": "Gia cầm bơi tốt, có mỏ dẹt.",
	"ngỗng": "Gia cầm lớn hơn vịt, cổ dài và kêu to.",

	"tam giác": "Hình phẳng có ba cạnh và ba góc.",
	"thang": "Hình tứ giác có một cặp cạnh đối song song.",
	"bình hành": "Hình tứ giác có hai cặp cạnh đối song song.",
	"thoi": "Hình tứ giác có bốn cạnh bằng nhau.",
	"chữ nhật": "Hình tứ giác có bốn góc vuông.",
	"vuông": "Hình có bốn cạnh bằng nhau và bốn góc vuông.",
	"đa giác": "Hình phẳng được tạo bởi nhiều đoạn thẳng khép kín.",
	"tròn": "Hình phẳng có mọi điểm trên đường bao cách đều tâm.",
	"elip": "Hình oval dẹt, giống đường tròn bị kéo dài.",
	"hộp chữ nhật": "Khối có sáu mặt đều là hình chữ nhật.",
	"lập phương": "Khối có sáu mặt đều là hình vuông bằng nhau.",
	"chóp": "Khối có đáy là đa giác và các mặt bên gặp nhau ở một đỉnh.",
	"nón": "Khối có đáy tròn và một đỉnh nhọn.",
	"cầu": "Khối tròn trong không gian, mọi điểm trên mặt cách đều tâm.",
	"trụ": "Khối có hai đáy tròn song song và mặt bên cong.",
	"lăng trụ": "Khối có hai đáy song song bằng nhau và các mặt bên là hình bình hành.",

	"mặt": "Phần trước của đầu, nơi có mắt, mũi và miệng.",
	"trán": "Phần phía trên khuôn mặt, dưới chân tóc.",
	"thái dương": "Vùng hai bên đầu, gần mắt và trán.",
	"tóc": "Lông mọc trên da đầu của con người.",
	"tai": "Bộ phận dùng để nghe, nằm hai bên đầu.",
	"dái tai": "Phần mềm phía dưới tai.",
	"mắt": "Bộ phận dùng để nhìn.",
	"mí mắt": "Nếp da che và bảo vệ mắt.",
	"tròng mắt": "Phần hình tròn nhìn thấy bên trong mắt.",
	"con ngươi": "Lỗ đen ở giữa mắt điều chỉnh lượng ánh sáng vào.",
	"lông mày": "Dải lông mọc phía trên mắt.",
	"lông mi": "Hàng lông nhỏ mọc ở viền mí mắt.",
	"má": "Phần hai bên khuôn mặt dưới mắt.",
	"mũi": "Bộ phận dùng để ngửi và thở.",
	"miệng": "Bộ phận dùng để ăn, nói và biểu cảm.",
	"môi": "Phần mềm bao quanh miệng.",
	"râu": "Lông mọc ở cằm, má hoặc quanh miệng nam giới.",
	"ria": "Lông mọc phía trên môi.",
	"cằm": "Phần dưới cùng của khuôn mặt.",
	"quai hàm": "Vùng xương hai bên hàm dưới.",
	"lúm đồng tiền": "Vết lõm nhỏ trên má khi cười.",
	"nốt ruồi": "Đốm nhỏ sẫm màu trên da.",

	"bảo thủ": "Không dễ tiếp nhận ý kiến mới, thường giữ cách nghĩ cũ.",
	"bi quan": "Có xu hướng nhìn sự việc theo hướng xấu hoặc thiếu hy vọng.",
	"bướng bỉnh": "Cố giữ ý mình dù người khác khuyên can.",
	"cẩn thận": "Làm việc kỹ lưỡng, chú ý tránh sai sót.",
	"cẩu thả": "Làm việc qua loa, thiếu chú ý đến chi tiết.",
	"cộc cằn": "Nói năng hoặc cư xử thô, thiếu mềm mỏng.",
	"cởi mở": "Dễ chia sẻ, dễ tiếp nhận điều mới và người mới.",
	"cứng đầu": "Khó thay đổi ý kiến dù có lý do thuyết phục.",
	"dễ gần": "Tạo cảm giác thân thiện, khiến người khác dễ trò chuyện.",
	"dễ tính": "Không quá khắt khe, dễ chấp nhận hoặc bỏ qua.",
	"dịu dàng": "Nhẹ nhàng trong lời nói, cử chỉ và cách cư xử.",
	"dối trá": "Không trung thực, thường nói sai sự thật.",
	"dũng cảm": "Dám đối mặt khó khăn, nguy hiểm hoặc thử thách.",
	"điềm tĩnh": "Giữ được bình tĩnh khi gặp tình huống căng thẳng.",
	"hài hước": "Có khả năng làm người khác cười bằng lời nói hoặc hành động.",
	"hào phóng": "Sẵn lòng chia sẻ, cho đi hoặc giúp đỡ.",
	"hăng hái": "Nhiệt tình và chủ động tham gia hoạt động.",
	"hậu đậu": "Vụng về, dễ làm rơi vỡ hoặc mắc lỗi nhỏ.",
	"hiền lành": "Tính tình nhẹ nhàng, ít gây hại hay xung đột.",
	"hiếu thắng": "Rất muốn thắng và khó chấp nhận thua.",
	"hòa đồng": "Dễ sống chung và hòa nhập với tập thể.",
	"hung dữ": "Dễ tấn công, đe dọa hoặc phản ứng mạnh.",
	"hướng ngoại": "Thích giao tiếp, hoạt động xã hội và gặp gỡ người khác.",
	"hướng nội": "Thích không gian riêng và thường suy nghĩ nhiều bên trong.",
	"ích kỷ": "Chỉ nghĩ đến lợi ích của bản thân.",
	"keo kiệt": "Quá tiết kiệm, không muốn chia sẻ tiền bạc hoặc vật chất.",
	"khiêm tốn": "Không khoe khoang, biết nhìn nhận giới hạn của mình.",
	"khó gần": "Tạo cảm giác xa cách, khiến người khác ngại tiếp xúc.",
	"kiêu căng": "Tự cao, coi mình hơn người khác.",
	"kiên nhẫn": "Có khả năng chờ đợi và bền bỉ trước khó khăn.",
	"lạc quan": "Có xu hướng nhìn sự việc theo hướng tốt đẹp.",
	"lạnh lùng": "Ít bộc lộ cảm xúc, tạo cảm giác xa cách.",
	"liều lĩnh": "Dám làm việc nguy hiểm mà ít cân nhắc hậu quả.",
	"lười biếng": "Ngại làm việc hoặc thiếu cố gắng.",
	"nghiêm khắc": "Đặt yêu cầu cao và ít dễ dãi với lỗi sai.",
	"nghiêm túc": "Cư xử đứng đắn, tập trung và không đùa cợt quá mức.",
	"nhút nhát": "Dễ ngại ngùng, thiếu tự tin khi tiếp xúc.",
	"nóng tính": "Dễ nổi giận hoặc phản ứng gắt.",
	"tham lam": "Muốn có nhiều hơn mức cần thiết hoặc công bằng.",
	"thẳng thắn": "Nói trực tiếp, rõ ràng điều mình nghĩ.",
	"thân thiện": "Cởi mở, dễ mến và tạo thiện cảm.",
	"thật thà": "Trung thực, không gian dối.",
	"tốt bụng": "Hay giúp đỡ và quan tâm người khác.",
	"trầm tính": "Ít nói, điềm đạm và không thích ồn ào.",
	"tử tế": "Cư xử đúng mực, biết quan tâm và tôn trọng người khác.",
	"tự tin": "Tin vào khả năng của bản thân.",
	"vui vẻ": "Có thái độ tươi tắn, dễ lan truyền cảm giác tích cực.",

	"bia": "Đồ uống có cồn nhẹ, lên men từ ngũ cốc.",
	"cà phê": "Đồ uống pha từ hạt rang xay, có vị đắng và hương thơm.",
	"cà phê đen": "Cà phê pha không thêm sữa, thường có vị đậm và đắng.",
	"cà phê phin": "Cà phê pha bằng dụng cụ lọc nhỏ giọt truyền thống.",
	"cà phê sữa": "Cà phê pha với sữa đặc hoặc sữa.",
	"nước cam": "Đồ uống vắt hoặc ép từ quả cam.",
	"nước chanh": "Đồ uống pha từ chanh, nước và thường thêm đường.",
	"nước dừa": "Chất lỏng trong quả dừa non, có vị ngọt mát.",
	"nước ép trái cây": "Đồ uống lấy nước từ trái cây tươi.",
	"nước khoáng": "Nước uống có chứa khoáng chất tự nhiên.",
	"nước lọc": "Nước sạch dùng để uống hằng ngày.",
	"rượu": "Đồ uống có cồn được lên men hoặc chưng cất.",
	"rượu vang": "Đồ uống có cồn lên men từ nho.",
	"sinh tố": "Đồ uống xay nhuyễn từ trái cây, đá, sữa hoặc đường.",
	"sinh tố cà chua": "Đồ uống xay từ cà chua, thường có vị chua nhẹ.",
	"sinh tố dâu": "Đồ uống xay từ dâu, thường có màu đỏ hồng và vị chua ngọt.",
	"sữa": "Đồ uống giàu dinh dưỡng lấy từ động vật hoặc thực vật.",
	"sữa bò": "Sữa lấy từ bò, thường dùng để uống hoặc chế biến thực phẩm.",
	"sữa đậu nành": "Đồ uống làm từ hạt đậu nành xay và nấu.",
	"trà": "Đồ uống pha từ lá trà hoặc thảo mộc.",
	"trà đá": "Trà pha loãng uống lạnh với đá.",
	"trà sữa": "Đồ uống pha từ trà, sữa và thường có thêm topping.",
	"trà thảo mộc": "Đồ uống pha từ lá, hoa hoặc rễ cây không nhất thiết là lá trà.",
	"trà xanh": "Trà làm từ lá trà ít oxy hóa, có màu xanh và vị chát nhẹ.",

	"cặp đôi": "Hai người có quan hệ yêu đương hoặc gắn bó tình cảm.",
	"mối tình đầu": "Tình yêu đầu tiên trong đời một người.",
	"người yêu": "Người có quan hệ tình cảm lãng mạn với mình.",
	"bạn trai": "Người nam trong quan hệ yêu đương.",
	"bạn gái": "Người nữ trong quan hệ yêu đương.",
	"tình địch": "Người cùng theo đuổi hoặc cạnh tranh trong chuyện tình cảm.",
	"cảm nắng": "Cảm giác thích ai đó nhanh chóng, thường mới chớm.",
	"tương tư": "Trạng thái nhớ nhung da diết một người mình yêu.",
	"yêu thầm": "Có tình cảm với ai đó nhưng không bộc lộ rõ.",
	"yêu đơn phương": "Yêu một người nhưng không được đáp lại tình cảm.",
	"hẹn hò": "Gặp gỡ riêng để tìm hiểu hoặc nuôi dưỡng tình cảm.",
	"nắm tay": "Hành động cầm tay nhau để thể hiện gần gũi.",
	"ôm": "Hành động vòng tay quanh người khác để thể hiện tình cảm.",
	"hôn": "Hành động chạm môi để thể hiện tình yêu hoặc sự thân mật.",
	"cãi nhau": "Tranh luận gay gắt vì bất đồng.",
	"chia tay": "Chấm dứt một mối quan hệ tình cảm.",
	"làm lành": "Hòa giải sau khi giận dỗi hoặc cãi nhau.",
	"tán tỉnh": "Nói hoặc làm điều để gây thiện cảm tình cảm với ai đó.",
	"tỏ tình": "Bày tỏ trực tiếp tình cảm yêu mến với người khác.",
	"thất tình": "Đau buồn vì tình yêu không thành hoặc tan vỡ.",
	"ngoại tình": "Có quan hệ tình cảm ngoài mối quan hệ đã cam kết.",
	"cắm sừng": "Cách nói dân gian về việc bị người yêu hoặc bạn đời phản bội.",

	"bắn cung": "Môn thể thao dùng cung bắn tên vào bia mục tiêu.",
	"bắn súng": "Môn thể thao dùng súng bắn vào bia với độ chính xác cao.",
	"bida": "Môn chơi dùng gậy đánh bi trên bàn phủ nỉ.",
	"bi sắt": "Môn ném các viên bi kim loại đến gần mục tiêu.",
	"bóng bàn": "Môn chơi dùng vợt nhỏ đánh bóng qua lưới trên bàn.",
	"bóng bầu dục": "Môn thể thao đối kháng dùng quả bóng bầu dục để ghi điểm.",
	"bóng chày": "Môn chơi dùng gậy đánh bóng rồi chạy qua các gôn.",
	"bóng chuyền": "Môn thể thao đánh bóng qua lưới bằng tay.",
	"bóng đá": "Môn thể thao hai đội dùng chân đưa bóng vào khung thành.",
	"bóng ném": "Môn thể thao dùng tay ném bóng vào khung thành.",
	"bóng rổ": "Môn thể thao ném bóng vào rổ treo cao.",
	"bowling": "Môn chơi lăn bóng để làm đổ các chai gỗ.",
	"bơi lội": "Hoạt động di chuyển trong nước bằng động tác tay chân.",
	"câu cá": "Hoạt động dùng cần, dây và mồi để bắt cá.",
	"cầu lông": "Môn thể thao dùng vợt đánh quả cầu qua lưới.",
	"cờ vua": "Trò chơi chiến thuật trên bàn 64 ô với vua, hậu, xe, mã, tượng, tốt.",
	"cử tạ": "Môn thể thao nâng tạ nặng theo kỹ thuật quy định.",
	"đánh gôn": "Môn thể thao dùng gậy đánh bóng vào lỗ trên sân rộng.",
	"đấm bốc": "Môn võ thi đấu bằng nắm đấm có găng.",
	"đấu bò": "Hoạt động đối đầu với bò trong đấu trường theo truyền thống một số nước.",
	"điền kinh": "Nhóm môn chạy, nhảy, ném và phối hợp trên sân vận động.",
	"đua mô tô": "Môn thi tốc độ bằng xe mô tô.",
	"đua ngựa": "Môn thi tốc độ giữa các ngựa và người cưỡi.",
	"đua thuyền": "Môn thi tốc độ bằng thuyền trên mặt nước.",
	"đua xe đạp": "Môn thi tốc độ hoặc sức bền bằng xe đạp.",
	"khúc côn cầu": "Môn thể thao dùng gậy đưa bóng hoặc đĩa vào khung thành.",
	"leo núi": "Hoạt động chinh phục vách đá hoặc địa hình núi.",
	"lướt sóng": "Môn thể thao đứng trên ván để trượt theo sóng biển.",
	"ném đĩa": "Môn điền kinh ném đĩa tròn đi xa.",
	"ném lao": "Môn điền kinh ném cây lao dài đi xa.",
	"nhảy cầu": "Môn thể thao bật nhảy từ bục cao xuống nước.",
	"nhảy dù": "Hoạt động nhảy từ trên cao và hạ xuống bằng dù.",
	"quần vợt": "Môn thể thao dùng vợt đánh bóng qua lưới trên sân.",
	"thể dục dụng cụ": "Môn biểu diễn động tác kỹ thuật trên xà, vòng, thảm hoặc dụng cụ.",
	"thể dục nhịp điệu": "Môn biểu diễn động tác theo nhạc với sự mềm dẻo và nhịp nhàng.",
	"trượt băng": "Hoạt động di chuyển trên băng bằng giày có lưỡi trượt.",
	"trượt tuyết": "Môn di chuyển trên tuyết bằng ván hoặc giày trượt.",
	"trượt ván": "Môn dùng ván có bánh để trượt và biểu diễn kỹ thuật.",
	"võ thuật": "Nhóm môn rèn luyện chiến đấu, tự vệ và kỹ thuật cơ thể.",
	"yoga": "Hoạt động luyện thân và tâm qua tư thế, hơi thở và sự tập trung.",

	"bướm": "Côn trùng có cánh lớn nhiều màu, phát triển từ sâu qua kén.",
	"bọ cánh cứng": "Côn trùng có đôi cánh trước cứng như vỏ bảo vệ.",
	"bọ chét": "Côn trùng rất nhỏ, nhảy xa và hút máu động vật.",
	"bọ hung": "Côn trùng cánh cứng, thường vê phân thành viên tròn.",
	"bọ ngựa": "Côn trùng có hai chân trước gập như tư thế cầu nguyện, săn mồi nhanh.",
	"bọ rùa": "Côn trùng nhỏ, thân tròn, thường có vỏ đỏ chấm đen.",
	"châu chấu": "Côn trùng nhảy xa, ăn lá cây và có chân sau phát triển.",
	"chuồn chuồn": "Côn trùng bay nhanh, thân dài, hai đôi cánh mỏng.",
	"dế": "Côn trùng nhỏ thường kêu rỉ rả, sống trong hang hoặc bụi cỏ.",
	"đom đóm": "Côn trùng có khả năng phát sáng ở phần bụng.",
	"gián": "Côn trùng thân dẹt, chạy nhanh, thường sống nơi ẩm tối.",
	"kiến": "Côn trùng sống theo đàn, có tổ và phân công rõ rệt.",
	"ong": "Côn trùng bay, nhiều loài hút mật và có ngòi đốt.",
	"mối": "Côn trùng sống theo đàn, thường ăn gỗ và vật liệu có cellulose.",
	"muỗi": "Côn trùng nhỏ bay được, con cái hút máu và có thể truyền bệnh.",
	"nhện": "Sinh vật tám chân, nhiều loài giăng tơ để bắt mồi.",
	"rận": "Sinh vật ký sinh nhỏ sống trên da hoặc tóc và hút máu.",
	"rệp": "Côn trùng nhỏ hút nhựa cây hoặc máu tùy loài.",
	"ruồi": "Côn trùng bay nhanh, thường xuất hiện quanh thức ăn hoặc rác.",
	"ve sầu": "Côn trùng kêu vang vào mùa nóng, sống lâu dưới đất khi còn ấu trùng.",

	"chòm sao": "Nhóm sao được tưởng tượng nối thành hình trên bầu trời.",
	"hành tinh": "Thiên thể quay quanh một ngôi sao và không tự phát sáng.",
	"tiểu hành tinh": "Thiên thể đá nhỏ quay quanh Mặt Trời.",
	"thiên thạch": "Mảnh vật chất từ không gian rơi vào khí quyển hoặc xuống đất.",
	"dải ngân hà": "Thiên hà chứa Hệ Mặt Trời của chúng ta.",
	"hố đen": "Vùng không gian có lực hấp dẫn mạnh đến mức ánh sáng khó thoát ra.",
	"hệ mặt trời": "Hệ gồm Mặt Trời và các thiên thể quay quanh nó.",
	"mặt trời": "Ngôi sao ở trung tâm Hệ Mặt Trời, cung cấp ánh sáng và nhiệt.",
	"sao thủy": "Hành tinh gần Mặt Trời nhất trong Hệ Mặt Trời.",
	"sao kim": "Hành tinh thứ hai từ Mặt Trời, sáng rõ trên bầu trời.",
	"trái đất": "Hành tinh nơi con người sinh sống.",
	"mặt trăng": "Vệ tinh tự nhiên của Trái Đất.",
	"sao hỏa": "Hành tinh đỏ, đứng thứ tư tính từ Mặt Trời.",
	"sao mộc": "Hành tinh lớn nhất trong Hệ Mặt Trời.",
	"sao thổ": "Hành tinh khí khổng lồ nổi bật với vành đai.",
	"sao thiên vương": "Hành tinh khí lạnh có trục quay nghiêng mạnh.",
	"sao hải vương": "Hành tinh xa, màu xanh, có gió rất mạnh.",
	"sao diêm vương": "Thiên thể từng được xếp là hành tinh, nay là hành tinh lùn.",
	"sao băng": "Vệt sáng do mảnh vật chất cháy khi lao vào khí quyển.",
	"sao chổi": "Thiên thể băng đá có đuôi sáng khi đến gần Mặt Trời.",
	"sao lùn trắng": "Tàn dư đặc và nóng của một ngôi sao sau giai đoạn tiến hóa.",
	"nhật thực": "Hiện tượng Mặt Trăng che khuất Mặt Trời khi nhìn từ Trái Đất.",
	"nguyệt thực": "Hiện tượng Trái Đất che ánh sáng Mặt Trời chiếu tới Mặt Trăng.",
	"chân không": "Không gian hầu như không có vật chất.",
	"khí quyển": "Lớp khí bao quanh một hành tinh.",
	"quỹ đạo": "Đường chuyển động của một thiên thể hoặc vật thể quanh vật khác.",
	"trọng lực": "Lực hút giữa các vật có khối lượng.",
	"tàu con thoi": "Tàu vũ trụ có thể phóng lên và trở về để tái sử dụng.",
	"tàu vũ trụ": "Phương tiện được chế tạo để hoạt động ngoài không gian.",
	"vệ tinh nhân tạo": "Thiết bị do con người phóng lên quỹ đạo để quan sát, liên lạc hoặc nghiên cứu.",

	"công nghệ": "Môn học về kỹ thuật, quy trình và cách ứng dụng công cụ vào đời sống.",
	"địa lý": "Môn học nghiên cứu Trái Đất, lãnh thổ, khí hậu và con người.",
	"giáo dục công dân": "Môn học về quyền, nghĩa vụ, đạo đức và pháp luật cơ bản.",
	"hóa học": "Môn học nghiên cứu chất, phản ứng và cấu tạo vật chất.",
	"lịch sử": "Môn học tìm hiểu sự kiện và quá trình phát triển của xã hội loài người.",
	"mỹ thuật": "Môn học rèn luyện cảm thụ và sáng tạo hình ảnh.",
	"ngoại ngữ": "Môn học về ngôn ngữ không phải tiếng mẹ đẻ.",
	"ngữ văn": "Môn học về tiếng Việt, văn bản và tác phẩm văn học.",
	"sinh học": "Môn học nghiên cứu sinh vật và sự sống.",
	"thể dục": "Môn học rèn luyện sức khỏe và vận động cơ thể.",
	"thủ công": "Môn học làm đồ vật bằng tay từ giấy, vải hoặc vật liệu đơn giản.",
	"tiếng anh": "Môn học về ngôn ngữ Anh.",
	"tin học": "Môn học về máy tính, dữ liệu và phần mềm.",
	"toán": "Môn học về số, hình, phép tính và tư duy logic.",
	"vật lý": "Môn học nghiên cứu lực, chuyển động, năng lượng và hiện tượng tự nhiên.",
	"kinh tế": "Môn học tìm hiểu sản xuất, tiêu dùng, thị trường và nguồn lực.",
	"triết học": "Môn học nghiên cứu các vấn đề nền tảng về thế giới, tư duy và con người.",

	"âm nhạc": "Nghệ thuật tổ chức âm thanh, giai điệu và nhịp điệu để biểu đạt cảm xúc.",
	"bài hát": "Tác phẩm âm nhạc có giai điệu và lời để hát.",
	"giai điệu": "Chuỗi âm cao thấp nối tiếp tạo nên nét nhạc dễ nhớ.",
	"giọng hát": "Âm thanh do con người phát ra khi hát.",
	"hòa âm": "Sự kết hợp nhiều âm vang cùng lúc để hỗ trợ giai điệu.",
	"lời bài hát": "Phần ngôn từ được hát trong một bài nhạc.",
	"nhạc cụ": "Dụng cụ dùng để tạo ra âm thanh âm nhạc.",
	"nhịp điệu": "Sự lặp lại có trật tự của phách mạnh, phách nhẹ và độ dài âm.",
	"nốt nhạc": "Ký hiệu hoặc âm đơn lẻ biểu thị cao độ và trường độ.",
	"đơn ca": "Hình thức hát một người.",
	"song ca": "Hình thức hát hai người.",
	"tam ca": "Hình thức hát ba người.",
	"tốp ca": "Hình thức hát theo nhóm nhiều người.",
	"ban nhạc": "Nhóm người cùng chơi nhạc hoặc biểu diễn âm nhạc.",
	"ca sĩ": "Người biểu diễn bài hát bằng giọng hát.",
	"dàn nhạc giao hưởng": "Tập hợp nhiều nhạc công chơi nhạc cổ điển quy mô lớn.",
	"nhà soạn nhạc": "Người sáng tác tác phẩm âm nhạc.",
	"nhạc sĩ": "Người sáng tác hoặc biểu diễn âm nhạc.",
	"lệch tông": "Tình trạng hát hoặc chơi nhạc sai cao độ so với tông chuẩn.",
	"nền": "Phần âm thanh hoặc nhạc phía sau hỗ trợ nội dung chính.",
	"cổ điển": "Thể loại âm nhạc có truyền thống lâu đời, cấu trúc chặt chẽ.",
	"dân ca": "Âm nhạc dân gian truyền miệng của một vùng hoặc cộng đồng.",
	"điện tử": "Thể loại âm nhạc tạo bằng thiết bị và âm thanh điện tử.",
	"hip hop": "Thể loại âm nhạc gắn với rap, nhịp mạnh và văn hóa đường phố.",
	"opera": "Loại hình sân khấu kết hợp hát, nhạc và diễn xuất.",
	"phim": "Tác phẩm hình ảnh động kể chuyện hoặc ghi lại sự kiện.",
	"pop": "Thể loại nhạc đại chúng, dễ nghe và phổ biến rộng rãi.",
	"rock": "Thể loại nhạc có tiết tấu mạnh, thường dùng guitar điện và trống.",
	"trữ tình": "Phong cách âm nhạc nhẹ nhàng, giàu cảm xúc.",
	"quốc ca": "Bài hát chính thức đại diện cho một quốc gia.",
	"thánh ca": "Bài hát tôn giáo dùng trong nghi lễ hoặc cầu nguyện.",
	"hát": "Hoạt động tạo âm nhạc bằng giọng người.",
	"khiêu vũ": "Hoạt động nhảy theo nhạc với động tác có nhịp điệu.",
	"nhảy múa": "Hoạt động chuyển động cơ thể theo nhạc để biểu diễn hoặc vui chơi.",
	"nghe nhạc": "Hoạt động thưởng thức âm thanh âm nhạc.",
	"chơi nhạc cụ": "Hoạt động tạo âm bằng nhạc cụ.",
	"sáng tác": "Việc tạo ra tác phẩm mới như bài hát, giai điệu hoặc lời nhạc.",
	"viết nhạc": "Việc ghi hoặc sáng tạo giai điệu, hòa âm và cấu trúc bài nhạc.",

	"ca nhạc": "Thể loại phim hoặc chương trình xoay quanh bài hát và biểu diễn âm nhạc.",
	"cổ trang": "Thể loại phim lấy bối cảnh thời xưa với trang phục và lễ nghi cổ.",
	"hành động": "Thể loại phim nhiều cảnh rượt đuổi, đánh nhau hoặc nhiệm vụ nguy hiểm.",
	"hình sự": "Thể loại phim về tội phạm, điều tra và phá án.",
	"hoạt hình": "Phim tạo bằng hình vẽ, mô hình hoặc đồ họa chuyển động.",
	"kinh dị": "Thể loại phim tạo cảm giác sợ hãi, căng thẳng hoặc rùng rợn.",
	"phiêu lưu mạo hiểm": "Thể loại phim theo chân nhân vật vượt qua hành trình nguy hiểm.",
	"tài liệu": "Phim ghi lại sự thật, nhân vật hoặc sự kiện có tính thông tin.",
	"tình cảm": "Thể loại phim tập trung vào cảm xúc và quan hệ giữa con người.",
	"trinh thám": "Thể loại phim xoay quanh bí ẩn, manh mối và suy luận phá án.",
	"viễn tưởng": "Thể loại phim tưởng tượng về công nghệ, tương lai hoặc thế giới khác.",
	"truyền hình": "Nội dung phim hoặc chương trình được phát trên hệ thống truyền hình.",
	"đạo diễn": "Người chỉ đạo nghệ thuật và cách thực hiện một bộ phim.",
	"diễn viên": "Người hóa thân thành nhân vật trong phim hoặc sân khấu.",
	"diễn viên chính": "Người đảm nhận vai trung tâm của câu chuyện.",
	"diễn viên phụ": "Người đảm nhận vai hỗ trợ cho tuyến nhân vật chính.",
	"diễn viên quần chúng": "Người xuất hiện trong cảnh đông người hoặc vai rất nhỏ.",
	"diễn viên đóng thế": "Người thay diễn viên thực hiện cảnh nguy hiểm hoặc kỹ thuật.",
	"diễn viên lồng tiếng": "Người dùng giọng nói để thể hiện lời thoại cho nhân vật.",
	"biên kịch": "Người viết kịch bản phim.",
	"người quay phim": "Người điều khiển máy quay và khung hình.",
	"ngôi sao điện ảnh": "Diễn viên nổi tiếng trong lĩnh vực phim ảnh.",
	"chuyển thể": "Việc biến tác phẩm từ dạng khác thành phim.",
	"cốt truyện": "Chuỗi sự kiện chính tạo nên nội dung phim.",
	"bối cảnh": "Không gian, thời gian và hoàn cảnh nơi câu chuyện diễn ra.",
	"kịch bản": "Văn bản ghi lời thoại, cảnh và hành động cho phim.",
	"cảnh quay": "Một đoạn hình ảnh được quay trong quá trình làm phim.",
	"kỹ xảo điện ảnh": "Hiệu ứng hình ảnh hoặc âm thanh tạo bằng kỹ thuật đặc biệt.",
	"diễn xuất": "Cách diễn viên thể hiện nhân vật qua lời nói, nét mặt và hành động.",
	"lồng tiếng": "Việc thu giọng nói thay cho âm thanh gốc của nhân vật.",
	"thuyết minh": "Giọng đọc giải thích hoặc kể lại nội dung trong phim.",
	"phụ đề": "Dòng chữ hiển thị lời thoại hoặc bản dịch trên màn hình.",
	"đoạn giới thiệu phim": "Video ngắn quảng bá và hé lộ nội dung phim.",
	"nhạc phim": "Âm nhạc được sáng tác hoặc chọn dùng cho phim.",
	"nhạc nền": "Âm nhạc phát phía sau để tạo cảm xúc cho cảnh phim.",
	"liên hoan phim": "Sự kiện trình chiếu, giao lưu và vinh danh các tác phẩm điện ảnh.",
	"giải thưởng điện ảnh": "Danh hiệu trao cho phim hoặc người làm phim xuất sắc.",
}

const THEME_CLUES: Dictionary = {
	"giáng sinh": {
		"ngôi sao": "Hình trang trí năm cánh, thường đặt trên đỉnh cây thông Noel.",
	},
	"vũ trụ": {
		"ngôi sao": "Thiên thể tự phát sáng nhờ năng lượng bên trong, nhìn thấy lấp lánh trên bầu trời đêm.",
	},
	"các kiểu tóc": {
		"ngắn": "Trạng thái tóc có độ dài ít, không phủ xa khỏi đầu.",
	},
	"phim ảnh": {
		"ngắn": "Dạng phim có thời lượng ngắn hơn phim dài thông thường.",
		"võ thuật": "Thể loại phim tập trung vào các màn chiến đấu tay chân và kỹ thuật võ.",
	},
	"nông trại": {
		"rìu": "Dụng cụ lưỡi nặng dùng để chặt củi, cây nhỏ hoặc vật liệu gỗ.",
	},
}

static func get_clue(word: String, theme_title: String = "") -> String:
	var clean_word: String = VietnameseNormalizer.clean_word(word)
	var clean_theme: String = VietnameseNormalizer.clean_word(theme_title)
	var theme_clues: Variant = THEME_CLUES.get(clean_theme)
	if typeof(theme_clues) == TYPE_DICTIONARY:
		var clue: String = String(theme_clues.get(clean_word, ""))
		if clue != "":
			return clue
	return String(CLUES.get(clean_word, ""))
